version: "3.8"
services:
  frontend:
    container_name: pokecoin-frontend
    build:
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true