version: '3.7'

services:
  pokecoin:
    image: skyprime17/pokecoin:latest
    container_name: pokecoin-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '7777:80'
